In [1]:
import numpy as np
import math

In [2]:
#criando matriz tridiagonal simetrica
n = int(input("Qual o tamanho da matriz"))

A = np.eye(n)*2
for i in range(0,n):
    if i>0:
        A[i,i-1]=-1
    if i<n-1:
        A[i,i+1]=-1

#criterio de parada de iteracoes
err=10**(-6)

In [3]:
#obtendo valores do seno e cosseno para a rotacao de givens
def get_givens_params(R, k):
    alfa = R[k,k]
    beta = R[k+1,k]
    if abs(alfa)>abs(beta):
        t = -beta/alfa 
        c = 1/((1+t**2)**(1/2))
        s=c*t
    else:
        t = -alfa/beta
        s = 1/((1+t**2)**(1/2))
        c=s*t
    return (c, s)

In [4]:
#obtendo cada transformacao de givens
def get_q(c, s, k, m):
    q=np.identity(m)
    q[k,k]=q[k+1,k+1]=c
    q[k,k+1]=-s
    q[k+1,k]=s
    return q  


In [5]:
#obtendo decomposicao QR
def get_qr_decomposition(A_):
    k=0
    R=A_
    m=np.size(A_,0)
    Q = np.identity(m)
    while k<=n-2:
        c,s = get_givens_params(R,k)
        q=get_q(c,s,k,m)
        Q = Q@(q.T)
        R=q@R
        k+=1
    return (Q, R)


In [6]:

#obtendo auto-valores e auto-vetores com ou sem (hasDesloc) deslocamento espectral
def qr_desloc(hasDesloc=False):
    V=np.identity(n)
    A_=A
    m=n
    u=0
    k=0
    
    #iteracao para cada auto-valor
    while m>=2:
        #iterando decomposicoes QR
        while abs(A_[m-1,m-2])>err:
            #definindo deslocamento espectral
            if k>0 and hasDesloc:
                d = (A_[m-2,m-2]-A_[m-1,m-1])/2
                sgn = np.sign(d or 1)
                u=A_[m-1,m-1]+d-sgn*(d**2+A_[m-1,m-2]**2)**(1/2)

            uI=u*np.identity(m)
            A_[0:m,0:m]-=uI
            Q,R = get_qr_decomposition(A_[0:m,0:m])
            A_[0:m,0:m]=R@Q+uI
            V[0:m,0:m]=V[0:m,0:m]@Q
            k+=1
        m-=1
        print(A_, V)

        autovalores = np.diag(A_)
        autovetores = V.T

    return (autovalores, autovetores)

vals, V = qr_desloc(True)
vals, V


[[3.00000000e+00 2.22044605e-16]
 [0.00000000e+00 1.00000000e+00]] [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


(array([3., 1.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [7]:
vals=[]
for i in range (1, n+1):
    l=2*(1-math.cos(i*math.pi/(n+1)))
    vals.append(l)
print(vals)

vets=[]
for i in range (1, n+1):
    vet = []
    for j in range (1, n+1):
        v=math.sin(i*j*math.pi/(n+1))
        vet.append(v)
    vets.append(vet)
print(vets)


[0.9999999999999998, 2.9999999999999996]
[[0.8660254037844386, 0.8660254037844387], [0.8660254037844387, -0.8660254037844385]]
